{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.ok.tracer",
    "module": "tracer-base",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ru.ok.tracer",
          "module": "tracer-platform",
          "version": {
            "requires": "1.1.7"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ru.ok.tracer",
          "module": "tracer-manifest",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "tracer-base-1.1.7.aar",
          "url": "tracer-base-1.1.7.aar",
          "size": 86951,
          "sha512": "24e4a4278107ad6794c7e714349f4f0dc08b4f4717257ef8288c1eba8106745c970e58ffdb56fd7a1acdf9ec16f440fdaa94080cd7241d8f6e1e95acff11f7b8",
          "sha256": "917ae590b2eb854d4e6f44bb7f110b970c6f08678b4fadbbc2cd64195b753f8d",
          "sha1": "6bc74ca4afbadd1d535d2cedfb1513ac25ab1a22",
          "md5": "463ef83d8ad2e53353ef2e0af2cab533"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ru.ok.tracer",
          "module": "tracer-platform",
          "version": {
            "requires": "1.1.7"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ru.ok.tracer",
          "module": "tracer-manifest",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracer-base-1.1.7.aar",
          "url": "tracer-base-1.1.7.aar",
          "size": 86951,
          "sha512": "24e4a4278107ad6794c7e714349f4f0dc08b4f4717257ef8288c1eba8106745c970e58ffdb56fd7a1acdf9ec16f440fdaa94080cd7241d8f6e1e95acff11f7b8",
          "sha256": "917ae590b2eb854d4e6f44bb7f110b970c6f08678b4fadbbc2cd64195b753f8d",
          "sha1": "6bc74ca4afbadd1d535d2cedfb1513ac25ab1a22",
          "md5": "463ef83d8ad2e53353ef2e0af2cab533"
        }
      ]
    }
  ]
}
